<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert(
            array([
                'id'            => 1,
                'code'          => '50010001',
                'Type_barcode'  => 'EAN13',
                'name'          => 'Cabe Rawit Merah',
                'cost'          => '5000',
                'price'         => '6000',
                'category_id'   => '5',
                'brand_id'      => 1,
                'unit_id'       => 1,
                'unit_sale_id'  => 1,
                'unit_purchase_id'  => 1,
                'stock_alert'   => '20',
                'tax_method'    => 2,
                'image'         => 'no-image.png',
            ],
            [
                'id'            => 2,
                'code'          => '50010002',
                'Type_barcode'  => 'EAN13',
                'name'          => 'Cabe Rawit Hijau',
                'cost'          => '5000',
                'price'         => '6000',
                'category_id'   => '5',
                'brand_id'      => 1,
                'unit_id'       => 1,
                'unit_sale_id'  => 1,
                'unit_purchase_id'  => 1,
                'stock_alert'   => '20',
                'tax_method'    => 2,
                'image'         => 'no-image.png',
            ],
            [
                'id'            => 3,
                'code'          => '50010003',
                'Type_barcode'  => 'EAN13',
                'name'          => 'Cabe Merah Keriting',
                'cost'          => '5000',
                'price'         => '6000',
                'category_id'   => '5',
                'brand_id'      => 1,
                'unit_id'       => 1,
                'unit_sale_id'  => 1,
                'unit_purchase_id'  => 1,
                'stock_alert'   => '20',
                'tax_method'    => 2,
                'image'         => 'no-image.png',
            ],
            [
                'id'            => 4,
                'code'          => '50010004',
                'Type_barcode'  => 'EAN13',
                'name'          => 'Cabe Hijau Keriting',
                'cost'          => '5000',
                'price'         => '6000',
                'category_id'   => '5',
                'brand_id'      => 1,
                'unit_id'       => 1,
                'unit_sale_id'  => 1,
                'unit_purchase_id'  => 1,
                'stock_alert'   => '20',
                'tax_method'    => 2,
                'image'         => 'no-image.png',
            ],
            [
                'id'            => 5,
                'code'          => '50020006',
                'Type_barcode'  => 'EAN13',
                'name'          => 'Bawang Merah',
                'cost'          => '5000',
                'price'         => '6000',
                'category_id'   => '5',
                'brand_id'      => 1,
                'unit_id'       => 1,
                'unit_sale_id'  => 1,
                'unit_purchase_id'  => 1,
                'stock_alert'   => '20',
                'tax_method'    => 2,
                'image'         => 'no-image.png',
            ],
            [
                'id'            => 6,
                'code'          => '50020007',
                'Type_barcode'  => 'EAN13',
                'name'          => 'Bawang Putih',
                'cost'          => '5000',
                'price'         => '6000',
                'category_id'   => '5',
                'brand_id'      => 1,
                'unit_id'       => 1,
                'unit_sale_id'  => 1,
                'unit_purchase_id'  => 1,
                'stock_alert'   => '20',
                'tax_method'    => 2,
                'image'         => 'no-image.png',
            ],
            [
                'id'            => 7,
                'code'          => '10010008',
                'Type_barcode'  => 'EAN13',
                'name'          => 'Kentang Sayur 250Gr',
                'cost'          => '5000',
                'price'         => '6000',
                'category_id'   => '1',
                'brand_id'      => 1,
                'unit_id'       => 1,
                'unit_sale_id'  => 1,
                'unit_purchase_id'  => 1,
                'stock_alert'   => '20',
                'tax_method'    => 2,
                'image'         => 'no-image.png',
            ],
            [
                'id'            => 8,
                'code'          => '10010009',
                'Type_barcode'  => 'EAN13',
                'name'          => 'Kangkung',
                'cost'          => '5000',
                'price'         => '6000',
                'category_id'   => '1',
                'brand_id'      => 1,
                'unit_id'       => 1,
                'unit_sale_id'  => 1,
                'unit_purchase_id'  => 1,
                'stock_alert'   => '20',
                'tax_method'    => 2,
                'image'         => 'no-image.png',
            ],
            [
                'id'            => 9,
                'code'          => '70010010',
                'Type_barcode'  => 'EAN13',
                'name'          => 'Paket Sayur Asem',
                'cost'          => '5000',
                'price'         => '6000',
                'category_id'   => '7',
                'brand_id'      => 1,
                'unit_id'       => 1,
                'unit_sale_id'  => 1,
                'unit_purchase_id'  => 1,
                'stock_alert'   => '20',
                'tax_method'    => 2,
                'image'         => 'no-image.png',
            ],
            [
                'id'            => 10,
                'code'          => '70010001',
                'Type_barcode'  => 'EAN13',
                'name'          => 'Paket Sayur Bening',
                'cost'          => '5000',
                'price'         => '6000',
                'category_id'   => '7',
                'brand_id'      => 1,
                'unit_id'       => 1,
                'unit_sale_id'  => 1,
                'unit_purchase_id'  => 1,
                'stock_alert'   => '20',
                'tax_method'    => 2,
                'image'         => 'no-image.png',
            ],
            [
                'id'            => 11,
                'code'          => '70010001',
                'Type_barcode'  => 'EAN13',
                'name'          => 'Paket Sayur Lodeh',
                'cost'          => '5000',
                'price'         => '6000',
                'category_id'   => '7',
                'brand_id'      => 1,
                'unit_id'       => 1,
                'unit_sale_id'  => 1,
                'unit_purchase_id'  => 1,
                'stock_alert'   => '20',
                'tax_method'    => 2,
                'image'         => 'no-image.png',
            ],
            [
                'id'            => 12,
                'code'          => '20010001',
                'Type_barcode'  => 'EAN13',
                'name'          => 'Tomat Merah',
                'cost'          => '5000',
                'price'         => '6000',
                'category_id'   => '2',
                'brand_id'      => 1,
                'unit_id'       => 1,
                'unit_sale_id'  => 1,
                'unit_purchase_id'  => 1,
                'stock_alert'   => '20',
                'tax_method'    => 2,
                'image'         => 'no-image.png',
            ],
            )
        );
    }
}
